apiVersion: apps/v1
kind: Deployment
metadata:
  name: coin-check
spec:
  selector:
    matchLabels:
      app: coin-check
  replicas: 1
  template:
    metadata:
      labels:
        app: coin-check
    spec:
      containers:
      - name: coin-check
        image: coin-check:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: reg-aws

